; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
build_unflags = -Werror -fuse-cxa-atexit
test_build_src = yes

[env:native]
platform = native
test_build_src = yes
build_flags = 
    -I test/mock
    -D PIO_UNIT_TESTING
build_src_filter = +<*> -<*> +<../src/alarm.cpp> +<../src/input.cpp> +<../src/system_state.cpp>